#!/usr/bin/env bash
#
## Create a temporary file to store module names
temp_file=$(mktemp)

# Find all .ex files in lib directory (excluding help.ex) and extract module names
find ./lib/qlarius -type f -name "*.ex" -not -path "./lib/qlarius/help.ex" | while read -r file; do
    # Extract module names from defmodule lines
    grep -h "^defmodule" "$file" | 
    sed 's/defmodule[[:space:]]*\([A-Za-z0-9._]*\).*/\1/' >> "$temp_file"
done

# Create the help.ex file with the module aliases
cat > ./lib/qlarius/help.ex << 'EOF'
# This file was auto-generated by update_help_module.sh
defmodule Qlarius.Help do
  defmacro __using__(_) do
    quote do
EOF

# Add each module as an alias
while IFS= read -r module; do
    # Skip empty lines
    [ -z "$module" ] && continue
    echo "      alias $module" >> ./lib/qlarius/help.ex
done < "$temp_file"

# Close the quote and module definition
cat >> ./lib/qlarius/help.ex << 'EOF'
    end
  end
end
EOF

# Clean up temporary file
rm "$temp_file"

echo "Updated lib/qlarius/help.ex with all module aliases"
