# This file was auto-generated by update_help_module.sh
defmodule Qlarius.Help do
  defmacro __using__(_) do
    quote do
      alias Qlarius.Wallets
      alias Qlarius.Surveys
      alias Qlarius.Arcade
      alias Qlarius.Campaigns
      alias Qlarius.Offers
      alias Qlarius.Arcade.Catalog
      alias Qlarius.Arcade.Creator
      alias Qlarius.Arcade.Tiqit
      alias Qlarius.Arcade.ContentPiece
      alias Qlarius.Arcade.TiqitClass
      alias Qlarius.Arcade.ContentGroup
      alias Qlarius.Traits.Trait
      alias Qlarius.Traits.TraitCategory
      alias Qlarius.Traits.UserTag
      alias Qlarius.Traits.TraitValue
      alias Qlarius.Media
      alias Qlarius.Marketing
      alias Qlarius.Release
      alias Qlarius.Offer
      alias Qlarius.MeFile
      alias Qlarius.Accounts
      alias Qlarius.AdEvent
      alias Qlarius.Accounts.User
      alias Qlarius.Accounts.Scope
      alias Qlarius.Accounts.UserNotifier
      alias Qlarius.Accounts.UserToken
      alias Qlarius.Accounts.MeFile
      alias Qlarius.Mailer
      alias Qlarius.Surveys.SurveyCategory
      alias Qlarius.Surveys.Survey
      alias Qlarius.Marketing.MediaSequence
      alias Qlarius.Marketing.MediaRun
      alias Qlarius.Marketing.MediaPiece
      alias Qlarius.Wallets.LedgerEntry
      alias Qlarius.Wallets.LedgerHeader
      alias Qlarius.Campaigns.AdCategory
      alias Qlarius.Campaigns.TargetBand
      alias Qlarius.Campaigns.TraitGroup
      alias Qlarius.Campaigns.Campaign
      alias Qlarius.Campaigns.Target
      alias Qlarius.Application
      alias Qlarius.Creators
      alias Qlarius.Repo
      alias Qlarius.Traits
    end
  end
end
