# This file was auto-generated by update_help_module.sh
defmodule Qlarius.Help do
  defmacro __using__(_) do
    quote do
      alias Qlarius.Sponster.Ads.AdCategory
      alias Qlarius.Sponster.Ads.MediaPiece
      alias Qlarius.Sponster.Ads.MediaPieceType
      alias Qlarius.Sponster.Ads.MediaPiecePhase
      alias Qlarius.Sponster.Ads.ThreeTap
      alias Qlarius.Sponster.Recipient
      alias Qlarius.Sponster.Marketing
      alias Qlarius.Sponster.Offer
      alias Qlarius.Sponster.AdEvent
      alias Qlarius.Sponster.Campaigns.TraitGroupTrait
      alias Qlarius.Sponster.Campaigns.MediaSequence
      alias Qlarius.Sponster.Campaigns.MediaRun
      alias Qlarius.Sponster.Campaigns.TargetBand
      alias Qlarius.Sponster.Campaigns.TraitGroup
      alias Qlarius.Sponster.Campaigns.Campaign
      alias Qlarius.Runtime.EnvLoader
      alias Qlarius.YouData.Traits.Trait
      alias Qlarius.YouData.MeFiles.MeFileTag
      alias Qlarius.YouData.MeFiles.MeFile
      alias Qlarius.YouData.Surveys.Surveys
      alias Qlarius.YouData.Surveys.SurveyCategory
      alias Qlarius.YouData.Surveys.Survey
      alias Qlarius.Accounts.Marketer
      alias Qlarius.Accounts.User
      alias Qlarius.Accounts.Users
      alias Qlarius.Accounts.Scope
      alias Qlarius.Accounts.UserProxy
      alias Qlarius.Wallets
      alias Qlarius.Wallets.LedgerEntry
      alias Qlarius.Wallets.LedgerHeader
      alias Qlarius.Application
      alias Qlarius.Tiqit.Arcade.Arcade
      alias Qlarius.Tiqit.Arcade.TiqitType
      alias Qlarius.Tiqit.Arcade.Tiqit
      alias Qlarius.Tiqit.Arcade.ContentPiece
      alias Qlarius.Tiqit.Arcade.ContentGroup
      alias Qlarius.Repo
    end
  end
end
