// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AppController from "./app_controller"
application.register("app", AppController)

import AppPageController from "./app_page_controller"
application.register("app-page", AppPageController)

import DobController from "./dob_controller"
application.register("dob", DobController)

import GenderCheckController from "./gender_check_controller"
application.register("gender-check", GenderCheckController)

import GuideSplideController from "./guide_splide_controller"
application.register("guide-splide", GuideSplideController)

import LinkJumpController from "./link_jump_controller"
application.register("link-jump", LinkJumpController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SignUpController from "./sign_up_controller"
application.register("sign-up", SignUpController)

import SurveySplideController from "./survey_splide_controller"
application.register("survey-splide", SurveySplideController)

import TagController from "./tag_controller"
application.register("tag", TagController)

import ThreeTapUnitController from "./three_tap_unit_controller"
application.register("three-tap-unit", ThreeTapUnitController)

import ZipCheckController from "./zip_check_controller"
application.register("zip-check", ZipCheckController)

import TipDrawerController from "./tip_drawer_controller"
application.register("tip-drawer", TipDrawerController)

