now = DateTime.utc_now(:second)

alias Qlarius.Campaigns.AdCategory
alias Qlarius.Repo

data = [
  "Auto Repair and Maintenance",
  "Dealership - Automobile",
  "Bank/Financial Institution",
  "Bar/Nightclub",
  "Beauty Services",
  "Beverages and Spirits",
  "Body Art",
  "Bookstore",
  "Charity",
  "Coffee Shop",
  "Convenience Store",
  "Credit Card",
  "Food/Grocery",
  "Food/Restaurant",
  "Gas/Fuel Station",
  "Hair Stylist/Barber",
  "Health/Fitness Club",
  "Health/Fitness Product",
  "ISP/Cable/Phone Provider",
  "Movie Rentals",
  "Movie Theater",
  "Non-profit Organization",
  "Public Service Announcement",
  "Real Estate - Locator Service",
  "Real Estate - Property",
  "Religious Organization",
  "Retail - Art Supply",
  "Retail - Clothing",
  "Retail - Collectibles",
  "Retail - Cosmetics",
  "Retail - Electronics",
  "Retail - Furniture",
  "Retail - Office Supply",
  "Retail - Specialty",
  "Retail - Specialty Clothing",
  "Retail - Sporting Goods",
  "Shopping Mall/Strip",
  "Special Event",
  "Specialty Drinks and Sweets",
  "Student Organization",
  "Supermarket",
  "Tutors & Study Aids",
  "University/Institution",
  "Utility Services",
  "Weight Loss Product",
  "Weight Loss Program",
  "Wireless/Cellular Carrier",
  "Wireless/Cellular Dealer",
  "Retailer - Beauty Supplies",
  "Retailer - Electronics & Appliances",
  "Manufacturer - Food Products - Specialty",
  "Ticket and Event Sales",
  "Dealership - Motorcycle",
  "Manufacturer - Personal Hygiene Products",
  "Manufacturer - Electronics & Appliances",
  "Website/Blog",
  "Household Cleaning Product",
  "Attorney/Legal Services",
  "Pet Care/Veterinary Services",
  "Service - Care and Sitters",
  "Specialty Product - Stationery",
  "Publisher - Magazine",
  "Insurance Agency/Services",
  "Retail - Department Store",
  "Service - Home Repair/Maintenance",
  "Book Publisher/Author",
  "Manufacturer - Automobiles",
  "Manufacturer - Apparel",
  "Wine, Beer, Spirits",
  "Soft Drinks/Water",
  "Food Product - Specialty",
  "Nursery/Garden Center",
  "Jewelry & Accessories",
  "Entertainment",
  "Health & Wellness",
  "Travel & Vacation",
  "Dentist/Orthodontist",
  "Pet Products",
  "Vision/Optical",
  "Museum/Exhibit",
  "Skin Care Product",
  "Software Publisher",
  "Identity Protection",
  "System Announcement",
  "Service - Advice/Life Coach",
  "Home Furnishings",
  "Specialty Product",
  "Contest",
  "Market Research",
  "Service  - Spa/Massage",
  "Auction/Online Auction",
  "Recreation",
  "Radio Station",
  "Florist",
  "School Organization",
  "Accounting/Tax Preparation",
  "Child Care - Specialty Product",
  "Theme/Amusement Park",
  "Wholesaler/Distributor",
  "Architecture/Design",
  "Military Services",
  "Sports/Entertainment Event",
  "Employment/Staffing",
  "Medical Device",
  "Swimming Pools/Supplies",
  "Toy Manufacterer/Retailer",
  "Service - Electrician/Electrical",
  "Service - Plumber/Plumbing",
  "Special Promotional Offer",
  "Service - Landscaping/Irrigation",
  "Educational Services",
  "Sports Memorabilia",
  "Home Maintenance Product",
  "Medical Device/Hearing",
  "Medical Practice/Facility",
  "Painters - Commercial/Residential",
  "Assisted Living Facility",
  "Automobile - Specialty Service",
  "Meeting/Event Facility",
  "Home Builder",
  "Mailing/Shipping",
  "Apparel",
  "Laundry/Dry Cleaning",
  "Musical Instruments",
  "*WELCOME - DEMO*",
  "Home Electronics",
  "Baby & Parenting Product"
]
|> Enum.map(&%{name: &1, inserted_at: now, updated_at: now})

Repo.insert_all(AdCategory, data)