import Config

# Configure your database
# Use DATABASE_URL if set, otherwise fall back to individual settings
database_config =
  if database_url = System.get_env("DATABASE_URL") do
    [
      url: database_url,
      ssl:
        String.contains?(database_url, "sslmode=require") or
          String.contains?(database_url, "amazonaws.com"),
      pool_size: 10
    ]
  else
    [
      username: "postgres",
      password: "postgres",
      hostname: "localhost",
      database: "qlarius_dev",
      stacktrace: true,
      show_sensitive_data_on_connection_error: true,
      pool_size: 10
    ]
  end

config :qlarius, Qlarius.Repo, database_config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
endpoint_config =
  [
    http: [ip: {0, 0, 0, 0}, port: 4000],
    https: [
      ip: {0, 0, 0, 0},
      port: 4001,
      cipher_suite: :compatible,
      keyfile: Path.expand("../priv/cert/localhost+2-key.pem", __DIR__),
      certfile: Path.expand("../priv/cert/localhost+2.pem", __DIR__)
    ],
    check_origin: false,
    # Force https://localhost:4001 locally: any request on the plain-http
    # :4000 listener 301s to the https listener. Keeps every local surface
    # (demosite, widget iframes, auth) on one canonical origin so the
    # Secure/SameSite=None session cookie always applies. HSTS is off so
    # the browser doesn't pin localhost to https for other projects.
    force_ssl: [hsts: false, host: "localhost:4001"],
    url: [host: "localhost", port: 4001, scheme: "https"],
    static_url: [host: "localhost", port: 4001, scheme: "https"],
    code_reloader: true,
    debug_errors: true,
    secret_key_base: "I0TNoNVsAUb60KoJZG27GA8uKP29XGc9Sifl6xY/RfCkULLRYLyl67A6PjHiYgoF",
    watchers: [
      esbuild: {Esbuild, :install_and_run, [:qlarius, ~w(--sourcemap=inline --watch)]},
      tailwind: {Tailwind, :install_and_run, [:qlarius, ~w(--watch)]}
    ]
  ]

config :qlarius, QlariusWeb.Endpoint, endpoint_config

# Override session for iframe support (requires HTTPS)
config :qlarius, QlariusWeb.Endpoint,
  session_options: [
    store: :cookie,
    key: "_qlarius_key",
    signing_salt: "Tvun6ICt",
    same_site: "None",
    secure: true
  ]

# Dev overrides: both Qlink surfaces collapse to localhost so dev/@alias works.
# The anon vs authed distinction is still enforced by the router host-scoping
# (via the mount callback), not by the host itself.
config :qlarius,
  qlink_share_host: "localhost:4001",
  qlink_interact_host: "localhost:4001",
  qlink_landing_redirect_url: "https://localhost:4001/",
  public_app_host: "localhost:4001",
  public_app_scheme: "https"

# Dev CORS extension IDs: includes the pinned dev extension ID alongside the
# legacy prod ID. Replace DEV_EXTENSION_ID_PLACEHOLDER once the extension build
# with a committed "key" field produces its deterministic ID (Phase 2.9).
config :qlarius,
  cors_extension_ids: [
    "chrome-extension://mhedmgbdabpgflgijpkabcdnkpncbdgp",
    "chrome-extension://DEV_EXTENSION_ID_PLACEHOLDER"
  ]

# Override Waffle to use HTTPS for asset URLs
config :waffle,
  asset_host: "https://localhost:4001"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
# Include all of `lib/qlarius_web/**` — the old pattern only matched
# controllers|live|components, so changes to layouts, endpoint, plugs, etc.
# recompiled but did not notify LiveReload (no auto refresh until manual reload).
config :qlarius, QlariusWeb.Endpoint,
  live_reload: [
    web_console_logger: false,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/qlarius_web/.*\.(ex|heex)$",
      ~r"lib/qlarius/.*\.ex$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :qlarius, dev_routes: true

# Log LiveView mount/reconnect, wallet PubSub sync, and socket events.
# Events -> tmp/lv_debug.ndjson — run `mix lv_debug.recent` after a refresh, or ask the agent to search that file.
config :qlarius, QlariusWeb.LiveViewDebug,
  enabled: true,
  log_path: "tmp/lv_debug.ndjson",
  max_log_bytes: 20 * 1024 * 1024

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :qlarius, debug_enabled: true

config :logger, level: :debug

# Carrier gate (AuthSheet pre-send + post-OTP): enforced when skip is off
# and US carrier filtering is on. Uses Twilio Lookup for unknown numbers.
config :qlarius, skip_carrier_validation: true
config :qlarius, :twilio_filter_us_carriers, true

# Set skip_carrier_validation: true ONLY to bypass Lookup while testing
# unrelated flows (disables the gate entirely).

# Phone verification bypass for development (skips Twilio entirely)
# Set to true when testing registration flow without real SMS
config :qlarius, bypass_phone_verification: true

# AuthSheet dev rollout. Enable on all three surfaces we have wired
# so far so B2+ in-place sign-in can be smoke-tested locally:
#   - `on_qlink_page` — qlink.qadabra.app / localhost qlink pages (B2)
#   - `on_qlinkin_bio` — qlinkin.bio (B6). Safe in dev because there's
#     no Cloudflare in front of localhost; production still defaults
#     off in config.exs until the CF cache rule is in place.
#   - `on_widget_standalone` — standalone arqade widget LVs
#     (/widgets/arqade/…).
# Production flags still default off in config.exs until staging
# promotion.
config :qlarius, :auth_sheet,
  on_qlink_page: true,
  on_qlinkin_bio: true,
  on_widget_standalone: true

config :qlarius, :in_app_browser_escape, enabled: true, auto_attempt: false
