import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :qlarius, QlariusWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  session_options: [
    store: :cookie,
    key: "_qlarius_key",
    signing_salt: "Tvun6ICt",
    same_site: "None",
    secure: true,
    http_only: true,
    max_age: 60 * 60 * 24 * 365
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Qlarius.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :qlarius, debug_enabled: false

# AuthSheet production rollout (B6 stage 2).
#
# Keyword-list values on `config :app, :key, ...` are merged at the
# key level (Mix.Config semantics), so this only flips the listed
# keys and leaves all other `:auth_sheet` defaults from config.exs
# (e.g. `on_qlink_page`, `on_widget_standalone`, `on_landing_pages`)
# untouched. Those stay gated separately.
#
# **Requires the Cloudflare cache rule "bypass cache when
# `_qlarius_web_user_remember_me` cookie is present on qlinkin.bio"
# to be active before deploying with this flag on**, otherwise
# authed visitors may be served cached anonymous HTML by the edge.
# See `docs/qlink_auth_refactor_plan.md` §B6 / rev 9.
config :qlarius, :auth_sheet, on_qlinkin_bio: true
