import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :qlarius, QlariusWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  session_options: [
    store: :cookie,
    key: "_qlarius_key",
    signing_salt: "Tvun6ICt",
    same_site: "None",
    secure: true,
    http_only: true,
    max_age: 60 * 60 * 24 * 365
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Qlarius.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :qlarius, debug_enabled: false

# AuthSheet production rollout (B6 stage 2).
#
# Keyword-list values on `config :app, :key, ...` are merged at the
# key level (Mix.Config semantics), so this replaces the listed keys
# on `:auth_sheet` and leaves unlisted keys (e.g. `on_landing_pages`)
# at their `config.exs` defaults.
#
# Both vanity (`qlinkin.bio`) and interact (`qlink.qadabra.app`, etc.)
# hosts enable in-place AuthSheet so visitors opening Qlinks from
# in-app browsers (Instagram, Reddit, …) can sign in without a
# separate prod gate on the interact host. Standalone publisher
# widgets use the same AuthSheet Connect interstitial → `/connect?popup=1`
# (or extension silent exchange) — not classic login/register.
#
# Originally this was documented as "requires a Cloudflare
# bypass-cache-when-authed rule first" — but a `curl -I` against
# qlinkin.bio showed Phoenix emits `cache-control: max-age=0,
# private, must-revalidate` on every session-carrying response
# (session-touching plugs: `:fetch_session` + `:protect_from_forgery`).
# CF respects `private` and serves everything as
# `cf-cache-status: DYNAMIC`. So there was never any risk of an
# authed response leaking to anon viewers via the edge cache —
# CF wasn't caching these responses to begin with.
#
# A Cloudflare bypass-on-remember-me rule is still useful as
# defense-in-depth if anyone ever overrides that cache-control
# header for perf reasons, but is not a prerequisite for this
# flag. See `docs/qlink_auth_refactor_plan.md` §B6 / rev 10.
# Interact Qlink host (qlink.qadabra.app / gigalixir qlink) uses
# `:on_qlink_page` — keep in sync with qlinkin.bio so in-app browsers
# (e.g. Reddit) get the same in-place AuthSheet as the vanity host.
config :qlarius, :auth_sheet,
  on_qlinkin_bio: true,
  on_qlink_page: true,
  on_widget_standalone: true
