---
title: Qlarius Data Model
---
erDiagram
    Campaign ||--o| MediaSequence : belongs_to
    Campaign ||--o| Target : belongs_to
    LedgerEntry ||--o| LedgerHeader : belongs_to
    LedgerHeader ||--o{ LedgerEntry : has
    LedgerHeader ||--o| User : belongs_to
    MediaPiece ||--o| AdCategory : belongs_to
    MediaRun ||--o| MediaPiece : belongs_to
    MediaRun ||--o| MediaSequence : belongs_to
    Offer ||--o| MediaPiece : belongs_to
    Offer ||--o| User : belongs_to
    Target ||--o{ Campaign : has
    Target ||--o{ TargetBand : has
    TargetBand ||--o| Target : belongs_to
    Trait }|--|{ User : has
    User ||--|| LedgerHeader : has
    User }|--|{ Trait : has
    UserToken ||--o| User : belongs_to

    Trait {
        string name
    }

    Offer {
        decimal phase_1_amount
        decimal phase_2_amount
        decimal amount
    }

    User {
        string email
        string password
        string hashed_password
        string current_password
        utc_datetime confirmed_at
    }

    UserToken {
        binary token
        string context
        string sent_to
    }

    MediaSequence {
        string title
        string description
    }

    MediaRun {
        integer frequency
        integer frequency_buffer_hours
        integer maximum_banner_count
        integer banner_retry_buffer_hours
    }

    MediaPiece {
        string title
        string body_copy
        string display_url
        string jump_url
    }

    LedgerEntry {
        decimal amount
        string description
    }

    AdCategory {
        string name
    }

    TargetBand {
        string title
        string description
        boolean bullseye
    }

    Campaign {
        string description
        string title
    }

    Target {
        string name
        string description
    }

    LedgerHeader {
        string description
        decimal balance
    }